### ISSUE TITLE
chat_timestamp error message

### ISSUE THREAD

**Issue by xBeret** [dastgirp/HPM-Plugins#35]
@dastgir  was testing its plugin Chat_TimeStamp I'm using client 2012-04-10 and it does not return me the time, the message appears as follows.

![Image](http://i64.tinypic.com/33wntkl.png)

**Comment by xBeret** [comment]
@dastgir

**Comment by dastgir** [comment]
Which configs are you using?
Party/guild/all/whispers?

**Comment by xBeret** [comment]
@dastgir All
