### ISSUE TITLE
sellitem2() causes NPCs to break

### ISSUE THREAD

**Issue by EyesOfAHawk** [dastgirp/HPM-Plugins#41]
Not sure if this is a new thing that has happened, but as soon as I use **sellitem2()** in any script, it will cause every NPC to break.

I used the script below, then all of a sudden I couldn't click any NPCs except the ones which were using sellitem2().
```
amatsu,110,95,3	trader	+10 Daggers	2_M_THIEFMASTER,{
OnInit:
	sellitem2(Combat_Knife, 1, 10, 0, 0, 0, 0, 0, 100000000);
	end;
}
```

**Comment by dastgirp** [comment]
Tried reproducing this error, couldn't, I can click normal NPC and trader npc
