### ISSUE TITLE
Critical Bug - Storage_Expand

### ISSUE THREAD

**Issue by Vaans** [dastgirp/HPM-Plugins#47]
This plugin have a critical bug that let you duplicate items.

How it works:

1.- Put items in your storage, for example two Jellopy
2.- change your character, always with the items in your storage
3.- Take off all the items in the storage, need to be 0 items in the storage.
4.- Change your character again
5.- Open your storage, two jellopy will appear in the storage

**Comment by dastgirp** [comment]
Can you check now @Vaans ?
