### ISSUE TITLE
Extending Vending

### ISSUE THREAD

**Issue by Aruar** [dastgirp/HPM-Plugins#50]
Hello, Dastgir. The ExtendedVending.c plugin is not functional in hexed 2018-06-21aRagexe. I tested it with other versions of 2018 and it also didn't work. I tested it in hexed 2015 and it worked normally

**Comment by dastgirp** [comment]
@Aruar 
It requires config in feature.conf. You need to put it at the end. Example:
```c
features: {
// Buying store (Note 1)
	// Requires: 2010-04-27aRagexeRE or later
	buying_store: true
......
}

// Enable Extended Vending System
extended_vending: 1

// Show Currency Name in the Pub of Vending
show_item_vending: 1

// Show Information about buying
ex_vending_info: 1

// ItemID for Zeny, 0 to disable
item_zeny: 30000

// ItemID for CashPoints, 0 to disable
item_cash: 30001
```

**Comment by dastgirp** [comment]
Closing as it is confirmed to be working
