### ISSUE TITLE
Compiling errors on a few plugins on latest Hercules

### ISSUE THREAD

**Issue by EPuncker** [dastgirp/HPM-Plugins#53]
Unmodified plugins and latest Hercules, on Windows 10 and Microsoft Visual Studio Community 2019

- **autoattack** plugin error: (https://i.imgur.com/AwJe8JO.png) (fixed on #57)
- ~~**dispbottom2** plugin compiles but with a warning: (https://i.imgur.com/hGKiwFe.png)~~ not needed at all since hercules have it by default

**Comment by dastgirp** [comment]
Closing as this is fixed.
