### ISSUE TITLE
Few warnings

### ISSUE THREAD

**Issue by Ducelina25** [dastgirp/HPM-Plugins#56]
CENTOS 7 - LINUX

@market

![market](https://user-images.githubusercontent.com/71337457/93231881-9e633400-f74f-11ea-8f88-1c81f2c8b465.png)

@noview

![noview](https://user-images.githubusercontent.com/71337457/93231862-97d4bc80-f74f-11ea-9db7-8412bcb04745.png)

I am new with plugins, and i cant fix this. Then i post here for your my friend.

**Comment by dastgirp** [comment]
@market should be fixed, second is normal warnings
