### ISSUE TITLE
Extended Vending Bug 2020-05-31 Herc

### ISSUE THREAD

**Issue by aero012** [dastgirp/HPM-Plugins#59]
First I tried this on Herc v2020.11.16 but after checking it doesn't work I realized I didn't check the version supported so I recheck and seen its only up to Herc 2020-06-01 so I used the 2020-05-31 but still doesn't work. 

So here's the scenario on buying and selling using the plugin system.
Zeny - Working [Buy and Sell] Both gets the item and profit
Cash Point - Working [Buy and Sell but items bought shows 'UNKNOWN ITEM' in dispbottom of the seller side] Both gets the item and profit. 
Custom Vend Item - Working [Buy Only]. On the seller side, he gets the profit/payment but immediately deleted.

This is the dispbottom info on the seller side.
> xxxx item(count) Sold.
> You get 'Custom Vend Item (count)'.
> Purchased 'Custom Vend Item (count)' has been deleted on inventory.  
> Buyer bought 'UNKNOWN ITEM' your total profit...
> Total revenue from ....

When I checked on the server side. Error show on sql_query updating the table `picklog` that data is out of range. So I checked the values its inserting, the data were negative values -92910 something like that.

**Comment by dastgirp** [comment]
Fixed @ https://github.com/dastgirp/HPM-Plugins/commit/0c12cef5de184a5683eba2f1fe9f8bf3a3dee7cd
